on: push
name: Slack Notification Demo
jobs:
  slackNotification:
    name: Slack Notification
    runs-on: ubuntu-latest
    steps:
    #- uses: actions/checkout@v2
    - name: Slack Notification
      uses: rtCamp/action-slack-notify@master
      env:
        SLACK_ICON: https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png
        SLACK_USERNAME: github-notification
        SLACK_FOOTER: Powered By CCS
        SLACK_WEBHOOK: ${{ secrets.MATTERMOST_WEBHOOK_URL }}
